### ISSUE TITLE
rake test fails for me

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/server-notifications-rails#1]
I might be doing this wrong, but when I run `rake test` I get two errors. Full output below:

```
abaker:server-notifications-rails abaker$ rake test
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.3/lib/bundler/runtime.rb:34:in `block in setup': You have already activated spring 1.3.6, but your Gemfile requires spring 1.3.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.3/lib/bundler/runtime.rb:19:in `setup'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.3/lib/bundler.rb:127:in `setup'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.3/lib/bundler/setup.rb:8:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/commands.rb:33:in `<module:Spring>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/commands.rb:4:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/server.rb:9:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
Run options: --seed 27295

# Running:

EE

Finished in 0.056682s, 35.2846 runs/s, 0.0000 assertions/s.

  1) Error:
NotificationsControllerTest#test_should_get_receiver:
ActionController::UrlGenerationError: No route matches {:action=>"receiver", :controller=>"notifications"}
    test/controllers/notifications_controller_test.rb:5:in `block in <class:NotificationsControllerTest>'


  2) Error:
NotificationsControllerTest#test_should_get_sender:
ActionController::UrlGenerationError: No route matches {:action=>"sender", :controller=>"notifications"}
    test/controllers/notifications_controller_test.rb:10:in `block in <class:NotificationsControllerTest>'

2 runs, 0 assertions, 0 failures, 2 errors, 0 skips
```

**Comment by jarodreyes** [comment]
Fixed here: https://github.com/TwilioDevEd/server-notifications-rails/commit/de88ad7642f2cd106d39bc3f6312562377af16fc
